from sqlalchemy import insert, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.academic_record import AcademicRecord


async def get_records_by_student(
    db: AsyncSession,
    student_id: int,
    semester: int | None = None,
) -> list[AcademicRecord]:
    q = select(AcademicRecord).where(AcademicRecord.student_id == student_id)
    if semester is not None:
        q = q.where(AcademicRecord.semester == semester)
    result = await db.execute(q)
    return list(result.scalars().all())


async def get_record(
    db: AsyncSession,
    student_id: int,
    subject_code: str,
    semester: int,
) -> AcademicRecord | None:
    result = await db.execute(
        select(AcademicRecord).where(
            AcademicRecord.student_id == student_id,
            AcademicRecord.subject_code == subject_code,
            AcademicRecord.semester == semester,
        )
    )
    return result.scalar_one_or_none()


async def create_record(
    db: AsyncSession,
    student_id: int,
    subject_code: str,
    subject_name: str,
    marks_obtained: float,
    max_marks: float,
    score_percent: float,
    performance_level: str,
    semester: int,
) -> AcademicRecord:
    await db.execute(
        insert(AcademicRecord).values(
            student_id=student_id,
            subject_code=subject_code,
            subject_name=subject_name,
            marks_obtained=marks_obtained,
            max_marks=max_marks,
            performance_level=performance_level,
            semester=semester,
        )
    )
    await db.flush()

    result = await db.execute(
        select(AcademicRecord).where(
            AcademicRecord.student_id == student_id,
            AcademicRecord.subject_code == subject_code,
            AcademicRecord.semester == semester,
        )
    )
    record = result.scalar_one()

    # For backends where score_percent is not generated by the DB (e.g. local SQLite),
    # persist the computed value so response serialization remains consistent.
    if record.score_percent is None:
        record.score_percent = score_percent
        await db.flush()

    return record
