"""baseline_existing_schema

Revision ID: fb6dbcd59d3f
Revises: 04f43c29744c
Create Date: 2026-04-20 14:56:22.712135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6dbcd59d3f'
down_revision: Union[str, None] = '04f43c29744c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_academic_records_student_semester'), table_name='academic_records')
    op.drop_index(op.f('idx_attendance_records_student_at_risk'), table_name='attendance_records')
    op.drop_index(op.f('idx_career_track_modules_track_sequence_order'), table_name='career_track_modules')
    op.drop_index(op.f('idx_learning_paths_student_is_current'), table_name='learning_paths')
    op.drop_index(op.f('idx_progress_student_path_status'), table_name='progress')
    op.alter_column('students', 'interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_subject_skill_mappings_subject_code'), table_name='subject_skill_mappings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_subject_skill_mappings_subject_code'), 'subject_skill_mappings', ['subject_code'], unique=False)
    op.alter_column('students', 'interests',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_index(op.f('idx_progress_student_path_status'), 'progress', ['student_id', 'path_id', 'status'], unique=False)
    op.create_index(op.f('idx_learning_paths_student_is_current'), 'learning_paths', ['student_id', 'is_current'], unique=False)
    op.create_index(op.f('idx_career_track_modules_track_sequence_order'), 'career_track_modules', ['track_id', 'sequence_order'], unique=False)
    op.create_index(op.f('idx_attendance_records_student_at_risk'), 'attendance_records', ['student_id', 'at_risk'], unique=False)
    op.create_index(op.f('idx_academic_records_student_semester'), 'academic_records', ['student_id', 'semester'], unique=False)
    # ### end Alembic commands ###
